version: "3.8"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack_s3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1